defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dev_defaults: &dev_defaults
  host: db
  username: user
  password: password

development:
  <<: [*defaults, *dev_defaults]
  
test:
  <<: [*defaults]

production:
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  prepared_statements: false
  advisory_locks: false
  sslmode: require
